---
swagger: "2.0"
info:
  description: "API Service that reads from Elasticsearch."
  version: "0.0.1"
  title: "Data Explorer Service"
  license:
    name: "BSD"
    url: "http://opensource.org/licenses/BSD-3-Clause"
paths:
  /dataset:
    get:
      tags:
      - "Dataset"
      description: "Gets dataset information, such as name."
      operationId: "dataset_get"
      parameters: []
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/DatasetResponse"
      x-swagger-router-controller: "data_explorer.controllers.dataset_controller"
  /facets:
    get:
      tags:
      - "Facets"
      description: "Returns facets."
      operationId: "facets_get"
      parameters:
      - name: "filter"
        in: "query"
        description: "filter represents selected facet values. Elasticsearch query\
          \ will be run only over selected facet values. filter is an array of strings,\
          \ where each string has the format \"esFieldName=facetValue\". Example url\
          \ /facets?filter=Gender=female,Region=northwest,Region=southwest\n"
        required: false
        type: "array"
        items:
          type: "string"
        collectionFormat: "pipes"
      - name: "extraFacets"
        in: "query"
        description: "extraFacets represents the fields selected from the field search\
          \ box. extraFacets is a list of Elasticsearch field names. In the returned\
          \ list of facets, the extra facets will come before the facets from ui.json."
        required: false
        type: "array"
        items:
          type: "string"
        collectionFormat: "pipes"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/FacetsResponse"
      x-swagger-router-controller: "data_explorer.controllers.facets_controller"
  /search:
    get:
      tags:
      - "Search"
      description: "Free text search over dataset"
      operationId: "search_get"
      parameters: []
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/SearchResponse"
      x-swagger-router-controller: "data_explorer.controllers.search_controller"
  /exportUrl:
    post:
      tags:
      - "ExportUrl"
      description: "Creates and returns a signed URL to a GCS zip file of JSON files.\
        \ The JSON files represent entities to be exported to a Terra workspace. https://app.terra.bio/#import-data\
        \ may be called with the url parameter  set to this url. For each JSON file,\
        \ https://rawls.dsde-prod.broadinstitute.org/#!/entities/create_entity may\
        \ be called with the JSON as the POST body.\n"
      operationId: "export_url_post"
      parameters:
      - in: "body"
        name: "exportUrlRequest"
        required: false
        schema:
          $ref: "#/definitions/exportUrlRequest"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/ExportUrlResponse"
      x-swagger-router-controller: "data_explorer.controllers.export_url_controller"
definitions:
  DatasetResponse:
    properties:
      name:
        type: "string"
      search_placeholder_text:
        type: "string"
        description: "What to show in the search box by default"
    description: "Dataset information."
    example:
      search_placeholder_text: "search_placeholder_text"
      name: "name"
  FacetsResponse:
    properties:
      facets:
        type: "array"
        items:
          $ref: "#/definitions/Facet"
      count:
        type: "integer"
        description: "Number of entities represented by current facet selection. For\
          \ example, this could be 40, representing 40 people.\n"
    description: "Results from a faceted search."
    example:
      count: 6
      facets:
      - values:
        - name: "name"
          count: 0
        - name: "name"
          count: 0
        name: "name"
        description: "description"
        es_field_name: "es_field_name"
      - values:
        - name: "name"
          count: 0
        - name: "name"
          count: 0
        name: "name"
        description: "description"
        es_field_name: "es_field_name"
  Facet:
    properties:
      name:
        type: "string"
        description: "Facet name, for example, \"Gender\"."
      description:
        type: "string"
        description: "Optional facet description."
      es_field_name:
        type: "string"
        description: "The Elasticsearch field name."
      values:
        type: "array"
        items:
          $ref: "#/definitions/FacetValue"
    description: "A facet. For example, the Gender facet would include the facet name\
      \ \"Gender\", as well as counts for all possible values.\n"
    example:
      values:
      - name: "name"
        count: 0
      - name: "name"
        count: 0
      name: "name"
      description: "description"
      es_field_name: "es_field_name"
  FacetValue:
    properties:
      name:
        type: "string"
        description: "Facet value name, for example, \"Male\"."
      count:
        type: "integer"
        description: "Facet value count."
    description: "A facet value, for example, \"Male\"/34."
    example:
      name: "name"
      count: 0
  ExportUrlResponse:
    properties:
      url:
        type: "string"
        description: "URL-encoded signed URL of GCS file containing entities to export."
      authorization_domain:
        type: "string"
        description: "Optional FireCloud authorization domain"
    description: "Information for sending data to Terra"
    example:
      authorization_domain: "authorization_domain"
      url: "url"
  SearchResponse:
    properties:
      search_results:
        type: "array"
        items:
          $ref: "#/definitions/SearchResult"
    example:
      search_results:
      - facet_value: "facet_value"
        elasticsearch_field_name: "elasticsearch_field_name"
        facet_name: "facet_name"
        facet_description: "facet_description"
      - facet_value: "facet_value"
        elasticsearch_field_name: "elasticsearch_field_name"
        facet_name: "facet_name"
        facet_description: "facet_description"
  SearchResult:
    properties:
      facet_name:
        type: "string"
        description: "The name of the facet."
      facet_description:
        type: "string"
        description: "Optional. The description of the facet."
      elasticsearch_field_name:
        type: "string"
        description: "The Elasticsearch field name."
      facet_value:
        type: "string"
        description: "If this search result represents a facet, facet_value is the\
          \ empty string. If this search result represents a facet and selected value,\
          \ facet_value is the selected value.\n"
    description: "Can represent a facet (Gender), or a facet and selected value (Gender\
      \ = female).\n"
    example:
      facet_value: "facet_value"
      elasticsearch_field_name: "elasticsearch_field_name"
      facet_name: "facet_name"
      facet_description: "facet_description"
  exportUrlRequest:
    type: "object"
    properties:
      cohortName:
        type: "string"
      filter:
        type: "array"
        items:
          type: "string"
